language: python
python:
 - 2.7
services:
 - docker

before_install:
- tar xvfz sandbox.tar.gz > /dev/null
- source sandbox/bin/activate
- sandbox/bin/pip install -r requirements.txt --exists-action w --upgrade
- BUILD_OPTS=--nopull make build_image

env:
- VERSION=leap42sp1 FLAVOR=products NOPULL=true TARGET=run CMD="sandbox/bin/py.test -c ./configs/suse/products/leap42sp1.cfg tests/"
- VERSION=leap42sp1 FLAVOR=products NOPULL=true TARGET=docker_run CMD="py.test -c ./configs/saltstack/products/unit.cfg /salt/src/salt-*/tests/"
- VERSION=leap42sp1 FLAVOR=products NOPULL=true TARGET=docker_run CMD="py.test -c ./configs/saltstack/products/integration.cfg /salt/src/salt-*/tests/"

script: make $TARGET
