language: python

python:
 - 2.7

services:
 - docker

before_install:
- pip install -r requirements.txt --exists-action w --upgrade
- pip install pytest

script: pylint --errors-only tests/* utils.py config.py 
