language: python

python:
         - 2.7

install:
        - pip install -r requirements.txt --exists-action w --upgrade
        - pip install pytest pylint pytest-factoryboy salt

script: pylint --errors-only tests/ utils.py config.py
