language: python
python:
 - 2.7
services:
 - docker

before_install:
- tar xvfz sandbox.tar.gz > /dev/null
- source sandbox/bin/activate
- sandbox/bin/pip install -r requirements.txt --exists-action w --upgrade

script:
- VERSION=leap42sp1 make -s build_image
- VERSION=leap42sp1 make -s custom_integration
